version: '3.4'

services:
  cyberAI:
    image: cyberai:latest
    build: 
      dockerfile: Dockerfile.project
      context: .
    hostname: cyberAI
    user: root
    ports:
      - "8501:8501"
    privileged: true
    working_dir: /opt/cyber_ai
    command:
      - /bin/bash
      - -c
      #- /root/anaconda/streamlit run app.py
      - tail -f /dev/null
